author = "gizak"
description = "a distraction-free hugo theme"
license = "MIT"
name = "nofancy"
source_repo = "https://github.com/gizak/nofancy"
tags = ["blog", "distraction-free"]

[author]
    name = "Zack Guo"
